services:
  compose:
    image: gaussian_splatting
    volumes:
      - ./:/workspace
      - /etc/sudoers.d:/etc/sudoers.d:ro
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      - DISPLAY
    # command: python3.10 train.py -s ./bicycle
    command: python3.10 render.py -m ./output/880b128b-d